extends Node


signal player_attack_location
signal new_round
signal player1_attack
signal ship_menu_opened
signal ship_menu_closed
signal Enemy_AI_Attacked
signal attack_button
signal quit_game
signal save_game
signal load_game
signal player_entered_port
signal player_exited_port
